In [19]:
import numpy as np

In [17]:
A= [[1,1],[2,2],[3,3],[4,4]]
k=[[1,2]]
z=[[1],[2]]

In [18]:
print(len(A), len(A[0]))

4 2


In [ ]:
def transpose(matrix):
    transposed=np.zeros((len(matrix[0]), len(matrix)))
    for i in range(len(matrix[0])):
        for j in range(len(matrix)):
            transposed[i][j]=matrix[j][i]
    return transposed
            

In [32]:
def matmul(x, y):
    x=np.asarray(x)
    y=np.asarray(y)
    if len(x[0])==len(y):
        result=np.zeros((len(x), len(y[0])))
        return x@y
    else:
        return None
    
    

In [28]:
print(matmul(A,transpose(k)))

[[ 3.]
 [ 6.]
 [ 9.]
 [12.]]


In [33]:
print(matmul(A, z))

[[ 3]
 [ 6]
 [ 9]
 [12]]


In [34]:
print(matmul(A, transpose(A)))

[[ 2.  4.  6.  8.]
 [ 4.  8. 12. 16.]
 [ 6. 12. 18. 24.]
 [ 8. 16. 24. 32.]]


In [36]:
def relu(matrix):
    return np.maximum(0, matrix)


In [38]:
b=[[1,0,0,0],[0,-2,0,0],[0,0,-1,0],[0,0,0,1]]
B=np.asarray(b)
print(relu(B))

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [ ]:
mat=np.asarray([[0,1],[1,1],[1,0],[0,0]])
target=np.asarray([[1],[1],[1],[0]])
weight=np.asarray(())

In [58]:
mat_with_intercept= np.c_[np.ones((len(mat),1)),mat]
print(mat_with_intercept)

[[1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 0.]]


In [ ]:
def predict(mat,target,weight):
    mat_with_intercept= np.c_[np.ones((len(mat),1)),mat]
    return np.linalg.inv(mat_with_intercept.T@ mat_with_intercept) @ mat_with_intercept.T @ target
    





In [63]:
weight=np.asarray([[0],[0],[0]])
print(predict(mat,  target, weight))

[[0.25]
 [0.5 ]
 [0.5 ]]


In [2]:
#Gradient descent (on the computer)

In [ ]:
def gradf(step_size,func, starting_point ,intercept):
    step_size=0.1
    fun= x1**2+ 2*x2**2
    